manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: r2d2rogers
      url-base: https://github.com/r2d2rogers
    - name: DiogoDoreto
      url-base: https://github.com/DiogoDoreto
  projects:
    - name: zmk
      remote: DiogoDoreto
      revision: waterfowl-encoders
      import: app/west.yml
  self:
    path: config
